### ISSUE TITLE
Error on updating a Custom Button

### ISSUE THREAD

**Issue by rnmatos** [alertmixer/amixr#1]
Hi! I've found an errror on updating a custom button.

I'm trying to integrate Amixr with StatusPage tool. 

Could you check it, please?

![image](https://user-images.githubusercontent.com/5869251/67297236-049ff200-f4c0-11e9-9389-fb746f741aaf.png)

**Comment by iskhakov** [comment]
Hi @rnmatos, 

The problem was on our side, to be concise the webhook url was a bit longer than we expected. Could you please try again, this issue should be fixed already.

**Comment by rnmatos** [comment]
It works. Thx.

**Comment by Matvey-Kuk** [comment]
@rnmatos thank you!
