### ISSUE TITLE
Multiple ical users does not work

### ISSUE THREAD

**Issue by gamer22026** [alertmixer/amixr#10]
Adding multiple users (space delimited) with same time range to an iCal results in only the first user showing up in Slack oncall rotation.
Adding multiple users with different time ranges to iCal results in the first user's time range showing in Slack oncall rotation correctly. When checking on-call schedule in slack for second user (for what should be a valid time range) it shows as "No one oncall" (Testing using Google calendar)

**Comment by Matvey-Kuk** [comment]
Thank you for the feedback! Will be fixed very soon.

**Comment by Matvey-Kuk** [comment]
@gamer22026 that should work now 🎉
