### ISSUE TITLE
phone call text-to speech sending same dat

### ISSUE THREAD

**Issue by gamer22026** [alertmixer/amixr#11]
The phone text to speech is:
1. Confusing. The ones I've received are of the form:
"2 in name percent 22 incident percent 22 triggered one times" The actual alert name was "#22 RabbitMqExchangeNoMessages via AlertManager". Not sure if what I'm receiving is what was you intended.
2. Sending the same text to speech message on different incident numbers. When incident #32 (#32 PodFrequentlyRestarting via AlertManager) was sent to phone as an escalation, it sent "2 in name percent 22 incident percent 22 triggered one times".

**Comment by Matvey-Kuk** [comment]
Thank you! We are checking.
