### ISSUE TITLE
Add 'delete whole incident' button

### ISSUE THREAD

**Issue by herewasmike** [alertmixer/amixr#15]
For now when i want to delete incident from channel I should also delete all messages in thread.
It would be more convenient to have single button to delete all (at least all from amixr) messages related to this incident
![image](https://user-images.githubusercontent.com/33277678/76974951-e6410400-6942-11ea-9cd7-bb3ee83e7605.png)

**Comment by Matvey-Kuk** [comment]
@herewasmike it's tricky because there could be user's messages in the thread and we want to make sure Amixr can't wipe any human-made content. But we'll make some intermediate solution.

Thank you for the request!

**Comment by Matvey-Kuk** [comment]
@herewasmike will be released in the API soon.

**Comment by Matvey-Kuk** [comment]
It's done over API: https://api-docs.amixr.io/#delete-incidents
