### ISSUE TITLE
User on schedule doesn't receive notifications

### ISSUE THREAD

**Issue by yelenabun** [alertmixer/amixr#16]
User on schedule is not either invited to alert nor receive the notification.

Alert
[https://www.dropbox.com/s/od68brljkyr42dm/0.png?dl=0](Alert)
Notification settings
[https://files.slack.com/files-pri/TTD9Q8FPF-F010CQ26KFT/image.png](Notification_settings)

Notification was sent after manually inviting user.

**Comment by Matvey-Kuk** [comment]
@yelenabun thank you for the report! We are checking.

**Comment by Matvey-Kuk** [comment]
We've closed the ticket in DM
