### ISSUE TITLE
Support webhook "notify by" target

### ISSUE THREAD

**Issue by tabascoterrier** [alertmixer/amixr#17]
Amixr looks great, but I could really do with a notification method that'll continue to nag me until I wake me up if I'm asleep.  I currently use Pushover for this, triggered via webhooks from other bits of monitoring software, and that works well.

Would you consider adding a webhook notification target so I could do a similar thing with Amixr?

**Comment by Matvey-Kuk** [comment]
@tabascoterrier thank you for the feedback!

Amixr is able to ping you until you respond a few times. Check "Personal notification preferences" here: https://amixr.io/app/admin/settings
<img width="609" alt="Screen Shot 2020-04-15 at 4 37 34 PM" src="https://user-images.githubusercontent.com/3284841/79343757-7c168180-7f37-11ea-917d-b167f5ca8494.png">

P.S. You could use webhook notification target in paid Amixr. We'll roll this feature to free users soon.

**Comment by tabascoterrier** [comment]
Ah, I didn't realise it was a paid feature - it's good to hear that Amixr can already do this, and even better to hear that'll be making it's way into the free plan!

I'll close this then as the feature already exists.
