### ISSUE TITLE
Settings appear ONLY if the browser window is full-screen

### ISSUE THREAD

**Issue by alexsss999** [alertmixer/amixr#19]
When you go to the Settings menu item on the right, a blank field appears with the warning "Configuration page is not supported on mobile device. Please open this page from desktop".

But I also work from a desktop environment. The Settings appear ONLY if the browser window is full-screen (expanded). Any other size does not display the Settings browser window.

I checked on browsers: seamonkey 2.49.1, firefox 57.0.1 (64-bit), Google Chrome
v. 70.0.3538.102 (Official Assembly) (64 bits).

HP ProBook 4730s 
display resolution 1600х900
OS Linux Fedora 25

**Comment by tclark** [comment]
I get the same issue with Firefox 83.0 (64 bit) on Mac OS 11.0.1

**Comment by Matvey-Kuk** [comment]
@tclark @alexsss999 thank you for your report. We'll prioritize mobile markup for the settings page
