### ISSUE TITLE
Can't create notification to private channel

### ISSUE THREAD

**Issue by iameliyahul** [alertmixer/amixr#20]
I create new private channel & add Amixr in it:

> Amixr.IO Incident ManagementAPP  6:58 AM
> was added to private_channel by Илья Литвинов.

Then I creat new integration & try to setup route to this channel, but got the error:

> Please choose a channel, make sure to invite Amixr if the channel is private.

**Comment by Matvey-Kuk** [comment]
It's fixed. Thank you for the report!
