### ISSUE TITLE
Using code block in postmortem case a misleading in the PM message

### ISSUE THREAD

**Issue by kuzaxak** [alertmixer/amixr#22]
![image](https://user-images.githubusercontent.com/5330267/80615227-130b2f80-8a48-11ea-97d1-66b8cc1e26f2.png)

Used text:

Should be fixed with upgrading node pools in Kubernetes console in Google Cloud.

```
Element	Value
{gitVersion="v1.13.11"}	1
{gitVersion="v1.14.10"}	24
{gitVersion="v1.13.7"}	1
{gitVersion="v1.12.6"}	2
```

**Comment by iskhakov** [comment]
Thank you for your feedback @kuzaxak! The issue is fixed
