### ISSUE TITLE
Group alert access to information

### ISSUE THREAD

**Issue by soloyes** [alertmixer/amixr#25]
It will be nice to have a possibility to get info about applications, which been grouped. For now this information posted into master issue body (to threads)

But this information we want to put into Jira's issue (summary, body, whatever)

Payload now is get from master issue, but this is not full case, when we have grouped alert.

**Comment by Matvey-Kuk** [comment]
@soloyes thank you, we've added {{ alert_payload }} to the Custom Button templating mechanism. The idea to add grouped alerts payloads is great. We'll take this into consideration during the next iteration of Custom Buttons!

**Comment by Matvey-Kuk** [comment]
Here is an example of template which gives alert payload:

```
{{ payload.text }}
\```
{{ payload | tojson_pretty }}
\```
```

**Comment by soloyes** [comment]
Templeate applied to root alert also duplicated to grouped. Awesome!
