### ISSUE TITLE
Alerts don't send because of strict json parsing

### ISSUE THREAD

**Issue by herewasmike** [alertmixer/amixr#3]
During integration I met following issue:

When I try to send alert using your [script](https://docs.amixr.io/#/integrations/zabbix?id=amixrsh-script) it doesn't work when message has new line special symbol.
e.g.
> $ ./amixr.sh https://app.amixr.io/integrations/v1/zabbix/{token}/ "Subject" "First line                                          
Second line"

Here's some curl trace parts:
>=> Send data, 92 bytes (0x5c)
0000: 7b 0a 20 20 20 20 22 74 69 74 6c 65 22 3a 20 22 {.    "title": "
0010: 53 75 62 6a 65 63 74 22 2c 0a 20 20 20 20 22 73 Subject",.    "s
0020: 74 61 74 65 22 3a 20 22 61 6c 65 72 74 69 6e 67 tate": "alerting
0030: 22 2c 0a 20 20 20 20 22 6d 65 73 73 61 67 65 22 ",.    "message"
0040: 3a 20 22 46 69 72 73 74 20 6c 69 6e 65 0a 53 65 : "First line.Se
0050: 63 6f 6e 64 20 6c 69 6e 65 22 0a 7d             cond line".}
== Info: We are completely uploaded and fine

>0000: 48 54 54 50 2f 32 20 34 30 30 20 0d 0a          HTTP/2 400 ..
<= Recv header, 32 bytes (0x20)

>0000: 7b 22 64 65 74 61 69 6c 22 3a 22 4a 53 4f 4e 20 {"detail":"JSON 
0010: 70 61 72 73 65 20 65 72 72 6f 72 20 2d 20 49 6e parse error - In
0020: 76 61 6c 69 64 20 63 6f 6e 74 72 6f 6c 20 63 68 valid control ch
0030: 61 72 61 63 74 65 72 20 61 74 3a 20 6c 69 6e 65 aracter at: line
0040: 20 34 20 63 6f 6c 75 6d 6e 20 32 37 20 28 63 68  4 column 27 (ch
0050: 61 72 20 37 37 29 22 7d                         ar 77)"}

So integration won't work in the way you described it.
![image](https://user-images.githubusercontent.com/33277678/68933229-48c3a100-07a5-11ea-839e-5eddd576feaa.png)

Though i resolved my issue with my own python script, i suppose you should update either manual or your script.

**Comment by Matvey-Kuk** [comment]
Thank you for your feedback! @iskhakov do you mind checking?

**Comment by iskhakov** [comment]
@herewasmike Thank you for a report! We've changed the script to handle such a situation:
```
subject="${2//$'\r\n'/'\n'}"
message="${3//$'\r\n'/'\n'}"
```

**Comment by Matvey-Kuk** [comment]
@iskhakov @herewasmike thank you!
