### ISSUE TITLE
Notifications about on-call 

### ISSUE THREAD

**Issue by ggerogery** [alertmixer/amixr#33]
Hi,
I would like to get automatic notifications based on iCal schedule. Like who is on-call now, and who is going to be next. It's good to have notification in specific Slack channel/direct messages.
Now I have to notify my colleagues manually, every week. I've tried Slack Google Cal and similar Apps, but it's not good for this task.

**Comment by Matvey-Kuk** [comment]
@ggerogery thank you for your request! We are already working on this feature. If everything will be ok it will be deployed next Wednesday. I'll keep you updated here.

**Comment by Matvey-Kuk** [comment]
This one is delivered! You'll be notified if you set Slack channel for Schedule. Looks like this:

<img width="475" alt="Screen Shot 2020-07-14 at 3 47 51 PM" src="https://user-images.githubusercontent.com/3284841/87427410-64f43800-c5e9-11ea-9419-138104820b98.png">
