### ISSUE TITLE
Amixr Terraform Provider v1

### ISSUE THREAD

**Issue by Matvey-Kuk** [alertmixer/amixr#36]
* [x] datasource for schedules
* [x] datasource for users
* [x] resource for escalations
* [x] resource for integrations
* [x] resource for routes
* [x] import
* [x] JInja templates for integraitons

Repo: https://github.com/alertmixer/terraform-provider-amixr

**Comment by clain23** [comment]
We'd want to be able to setup jinja templates for integrations to keep them in sync for similar integration types.

**Comment by Matvey-Kuk** [comment]
@clain23 thx! Jinja templates are planned for v2. 

https://github.com/alertmixer/amixr/issues/38

**Comment by Matvey-Kuk** [comment]
Jinja templates moved to V1 🎉

**Comment by Matvey-Kuk** [comment]
This one is ready. We are waiting for Hashicorp approval but feel free to compile and use!
