### ISSUE TITLE
Resolved incidents don't showed on dashboard

### ISSUE THREAD

**Issue by herewasmike** [alertmixer/amixr#4]
Nothing is returned. Only load icon
![image](https://user-images.githubusercontent.com/33277678/68934401-b1ac1880-07a7-11ea-8b89-d821af9a3e40.png)

**Comment by Matvey-Kuk** [comment]
@herewasmike thank you for your bugreport! We've detected the issue on our side. I'll let you know once it's fixed. 

P.S.: Please note that the dashboard you see is a pre-release version for early-access users.

**Comment by iskhakov** [comment]
@herewasmike thanks for reporting that, all fixed, should be working for you now! Can you please check?

**Comment by herewasmike** [comment]
It's good, thank you for fast resolution

**Comment by Matvey-Kuk** [comment]
@iskhakov @herewasmike thank you! Closing.
