### ISSUE TITLE
Bulk ack, resolve, unack

### ISSUE THREAD

**Issue by Matvey-Kuk** [alertmixer/amixr#41]
Client's request. I guess it should go to web.

**Comment by soloyes** [comment]
- Web
- /amixr command also very useful
- also API of course

**Comment by Ekaterina-Eg** [comment]
Hi, @soloyes , here is our update:

* Web
Bulk update on Amixr Incidents tab.
The interface has been improved with checkboxes ☑️ and buttons above the incidents table. Select incidents individually or select all at once then acknowledge/resolve them in a flash.
There is also a restart button 🔄  if you want to unresolve and unacknowledge a bulk of incidents.

* /amixr command also very useful
Unfortunately, this wasn't included in the current release, we will create a separate issue for this feature.

* also API of course
This release doesn’t include bulk API, currently, the only single incident action is available, we suggest using it in the loop, our rate limit is quite friendly 😃
