### ISSUE TITLE
Custom actions (ex Custom Buttons or external webhooks) v2

### ISSUE THREAD

**Issue by Matvey-Kuk** [alertmixer/amixr#42]
Design TBD.

Client's request: Ack in the incident source (Zabbix):
For now we have ack webhook as an argument `ack_url` for https://docs.amixr.io/#/integrations/formatted_webhook?id=on-integration-side . I guess it should be able to achieve using next gen Custom Actions

**Comment by soloyes** [comment]
Best way ack with some payload + with Jira's issue link (created by custom button)

**Comment by Matvey-Kuk** [comment]
```
Amixr -> generate ticket in Jira -> publish ticket to Zabbix
```
