### ISSUE TITLE
Too many escalations in incident timeline with "notify channel"

### ISSUE THREAD

**Issue by herewasmike** [alertmixer/amixr#6]
I can see all slack space users in incident report even though they're not invited in notified channel.
I suppose there should be only one record for channel escalation.
>Resolved by @user_not_found.```Timeline:
>- 0 seconds: incident registered
>- a second: escalation triggered for @mike
>- 30 minutes: escalation triggered for @***
>- 30 minutes: escalation triggered for @***
>- 30 minutes: escalation triggered for @***
>- 30 minutes: escalation triggered for @***
>- 30…

**Comment by Matvey-Kuk** [comment]
@herewasmike the purpose is to make a record about who exactly was in channel at this moment. But we'll think about making it more compact, thank you!

**Comment by herewasmike** [comment]
Unfortunately this is more looks like bug than feature request for me cause I saw every slack user "even though they're not invited in notified channel"

**Comment by Matvey-Kuk** [comment]
Whoops, it was fixed some time ago. Sorry for the late response!
