### ISSUE TITLE
Resolve main incident only when all grouped resolved

### ISSUE THREAD

**Issue by herewasmike** [alertmixer/amixr#7]
For now if first of N grouped alerts resolved all incidents are considered as resolved.
This is quite tricky and may lead to some missed escalations.
Is there a chance for this feature request?

**Comment by Matvey-Kuk** [comment]
May I ask which integration are you talking about? For example for alertmanager incident will be resolved only once all label combinations are resolved :)

**Comment by herewasmike** [comment]
It's about zabbix integration.
Alertmanager works fine

**Comment by Matvey-Kuk** [comment]
@herewasmike we started planning this feature :)

**Comment by herewasmike** [comment]
Any updates on this so far?
