### ISSUE TITLE
Send slack channel & user ID in custom button webhook

### ISSUE THREAD

**Issue by bitdriftr** [alertmixer/amixr#72]
Hi,

In order to implement a solution using Alert Mixer's custom buttons, I need :
- the slack ID of the channel the button was clicked in (to be able to send messages in it)
- the slack username of the user that clicked the button (to be able to log who's doing what)

Could these informations be sent into the custom button webhook?

**Comment by Matvey-Kuk** [comment]
@arcln thank you for the ticket! It's not available in the current implementation but we'll take this request into account for the v2 of "custom buttons". I'll keep you updated on this thread.
