### ISSUE TITLE
iCal schedule url field is limited to 150 characters

### ISSUE THREAD

**Issue by gamer22026** [alertmixer/amixr#8]
Was trying to integrate iCal from office365 but adding URL failed with 150 character limit for that field. The URL provided by Office365 for iCal was 205 characters

**Comment by Matvey-Kuk** [comment]
Thank you for your request! We scheduled a fix for the next update. I'll let you know once it's deployed :)

**Comment by Matvey-Kuk** [comment]
@gamer22026 fixed, thank you!
