### ISSUE TITLE
Incorrect redirecting after Login

### ISSUE THREAD

**Issue by aladmit** [alertmixer/amixr#81]
It redirects to HTTP page http://amixr.io/app/auth/login which never loads, insted of https, after clicking LOGIN button on https://amixr.io/ page.

Page just stuck in loading and there is a lot of CORS and redirecting errors. The only way to open dashboard is to manually change http to https in url.

<img width="1348" alt="Screenshot 2021-04-28 at 16 30 31" src="https://user-images.githubusercontent.com/4015182/116412145-10037480-a83f-11eb-80bc-8d2edf7ae0bf.png">

My specs:
MacOS 11.2.3
Firefox Developer Edition 89.05b

**Comment by Matvey-Kuk** [comment]
Fixed, thank you for the report!
