### ISSUE TITLE
Incident creation with slack bot doesn't add a message

### ISSUE THREAD

**Issue by vutratenko** [alertmixer/amixr#82]
Hi Team,

When I'm trying to create an incident with Slack command /incident Slack bot creates an incident without a message.

Here are my steps to reproduce:

1. Hit the Slack command `/incident Test Incident Name`
2. In modal window ensure that **Title** field is _Test Incident Name_
3. Fill **Message** field with some content: _This is a test incident_ in my case
4. Hit the **Submit** button
5. ???
6. See the incident without a message

Please see screenshots attached.

<img width="591" alt="Screenshot 2021-05-04 at 18 46 55" src="https://user-images.githubusercontent.com/23396935/117036330-f9ad5b00-ad0d-11eb-8c3b-bcd8137ccd04.png">
<img width="591" alt="Screenshot 2021-05-04 at 18 54 16" src="https://user-images.githubusercontent.com/23396935/117036409-12b60c00-ad0e-11eb-9965-0d3e344ce8f4.png">

**Comment by Konstantinov-Innokentii** [comment]
Thank you for reporting  the bug, we fixed this one.
