### ISSUE TITLE
Amixr heartbeat incident not resolved

### ISSUE THREAD

**Issue by Tassatux** [alertmixer/amixr#85]
Hello,

I've enabled heartbeat (https://docs.amixr.io/#/integrations/heartbeat) to make sure I notice if my Alertmanager go down. When testing it, I've got both "Heartbeat is missing" and "Heartbeat restored" notification, but the incident was not resolved as it should according to the doc.

I've retrieved disabling heartbeat on Alertmanager side few day after to see if this was a temporary issue, but alert got grouped on the same incident and it's still unresolved:

![amixr_heartbeat_incident](https://user-images.githubusercontent.com/1558396/125250222-473dd980-e2f6-11eb-81a3-7457b4c2a294.png)

**Comment by Konstantinov-Innokentii** [comment]
Hi, looks like autoresolve is disabled for your integration. I checked, it is enabled now,  does problem still exist?

**Comment by Tassatux** [comment]
Hi,

I've checked again, but the incident stay unresolved:
![image](https://user-images.githubusercontent.com/1558396/137135667-444b534b-1085-414d-902e-17aa79075373.png)

About the autoresolve, it seemed already enabled as incident opened via a Prometheus alert were properly closed when the alert was resolved.
Only the heartbeat seem to have this issue.

**Comment by sobolevskaya-k** [comment]
hi, do you have any updates? we have the same problem. we have 2 alerts, first of both is firing and second resolved
@Tassatux @Konstantinov-Innokentii

**Comment by Matvey-Kuk** [comment]
Please file the issue in OnCall repo: https://github.com/grafana/oncall
