### ISSUE TITLE
Register Prom's watchdog as a heartbeat in Amixr

### ISSUE THREAD

**Issue by Matvey-Kuk** [alertmixer/amixr#9]
Prometheus has "watchdog" functionality, Amixr has heartbeats (https://docs.amixr.io/#/integrations/heartbeat). 

Related: https://github.com/helm/charts/pull/11617/files#diff-541ef4e669dec0cd9643e6a7c1ffab01R32

**Comment by varuzam** [comment]
is there any update on the issue?
